# Generated by Django 5.0.2 on 2024-04-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0002_alter_flower_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="flower",
            name="user",
        ),
        migrations.AddField(
            model_name="flower",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name="flower",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="flower",
            name="title",
            field=models.CharField(default="Rose", max_length=50),
        ),
    ]
