# Generated by Django 5.0.2 on 2024-04-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0003_remove_flower_user_flower_price_flower_quantity_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flower",
            name="details",
            field=models.TextField(),
        ),
    ]
